/**
 * Códigos de permisos del sistema CIDCA
 * Cada permiso es validado en los Server Actions
 */

export const PERMISSION_CODES = {
  // Gestión de Cursos
  CREAR_CURSO: 'CREAR_CURSO',
  EDITAR_CURSO: 'EDITAR_CURSO',
  VER_CURSO: 'VER_CURSO',
  ELIMINAR_CURSO: 'ELIMINAR_CURSO',

  // Gestión de Módulos y Apartados
  CREAR_MODULO: 'CREAR_MODULO',
  EDITAR_MODULO: 'EDITAR_MODULO',
  VER_MODULO: 'VER_MODULO',
  ELIMINAR_MODULO: 'ELIMINAR_MODULO',

  // Gestión de Exámenes
  CREAR_EXAMEN: 'CREAR_EXAMEN',
  EDITAR_EXAMEN: 'EDITAR_EXAMEN',
  VER_EXAMEN: 'VER_EXAMEN',
  RESPONDER_EXAMEN: 'RESPONDER_EXAMEN',
  CALIFICAR_EXAMEN: 'CALIFICAR_EXAMEN',

  // Gestión de Asistencia
  REGISTRAR_ASISTENCIA: 'REGISTRAR_ASISTENCIA',
  VER_ASISTENCIA: 'VER_ASISTENCIA',
  EDITAR_ASISTENCIA: 'EDITAR_ASISTENCIA',

  // Gestión de Estudiantes
  VER_ESTUDIANTES: 'VER_ESTUDIANTES',
  INSCRIBIR_ESTUDIANTE: 'INSCRIBIR_ESTUDIANTE',

  // Reportes
  VER_REPORTES: 'VER_REPORTES',
  GENERAR_CERTIFICADOS: 'GENERAR_CERTIFICADOS',

  // Admin
  ADMINISTRAR_SISTEMA: 'ADMINISTRAR_SISTEMA',
} as const;

export const ROLE_NAMES = {
  SISTEMAS: 'SISTEMAS',
  DOCENTE: 'DOCENTE',
  ESTUDIANTE: 'ESTUDIANTE',
  ADMINISTRADOR: 'ADMINISTRADOR',
} as const;

export type PermissionCode = typeof PERMISSION_CODES[keyof typeof PERMISSION_CODES];
export type RoleName = typeof ROLE_NAMES[keyof typeof ROLE_NAMES];
